version: 0.0
os: linux
files:
  - source: /
    # S3에서 가져온 파일을 저장할 위치
    destination: /home/ubuntu/dm2023-next
    # 덮어쓰기 옵션
    overwrite: yes

# files에서 가져온 파일들에게 권한을 어떻게 적용해야하는지 지정하는 곳입니다.
permissions:
  - object: /
    pattern: '**'
    owner: ubuntu
    group: ubuntu

hooks:
  BeforeInstall:
    - location: scripts/before-install.sh
      timeout: 600
      runas: ubuntu
  AfterInstall:
    - location: scripts/after-install.sh
      timeout: 4000
      runas: ubuntu
