version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: proxy
    network_mode: "host"
    restart: "always"
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./robots.txt:/usr/share/nginx/html/robots.txt

  dm2023-next:
    build: .
    container_name: dm2023-next
    restart: always
    ports:
      - '3000:3000'